version: "3.7"
services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:10
    volumes:
      - app-db:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    environment:
       POSTGRES_DB: postgres
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
volumes:
  app-db:
    name: app-db